// js/courseData.js

const ALL_COURSES = [
    // ===== Period 1 =====
    "Biology, CP",
    "Geometry, Honors",
    "Instrumental Music I (Fall) / Instrumental Music II(Spring)",
    "Chemistry, Honors",
    "Modern World History, CP",
    "Financial Literacy (Fall)/ Intro to Business (Spring)",
    "SAT English (Spring)",
    "SAT Math (Fall)/SAT Math (Spring)",
    "English 11, Honors",
    "PE/Health (Fall) / PE/Health (Spring)",
    "Spanish IV, Honors",
    "Arabic III & IV, Honors",
    "Essay Writing for Seniors (Fall)",
    "AP Statistics",
    "Cybersecurity",
  
    // ===== Period 2 =====
    "Algebra I",
    "Geometry, CP",
    "Graphic Design - Full Year",
    "Modern World History, CP",
    "English 10, Honors",
    "Honors Precalculus",
    "Spanish III, Honors",
    "Anatomy and Physiology",
    "Instrumental Music I (Fall) / Instrumental Music II(Spring)",
    "National & International Current Affairs (Fall) / Public Speaking (Spring)",
    "English 12, CP",
    "AP US History",
    "Broadcast Media Production",
    "Dynamic Programming",
  
    // ===== Period 3 =====
    "Spanish I /Arabic I /Turkish I / Chinese I / French I (Independent Study with a Supervisor)",
    "English 9, Honors",
    "Digital Visual Art (Fall) / Cultivating Creativity (Spring)",
    "Instrumental Music I (Fall) / Instrumental Music II(Spring)",
    "English 10, CP",
    "AP Precalculus",
    "Chemistry, CP",
    "Web Development I (Fall)/Web Development II",
    "Sociology of the Future (Fall) / Global Issues (Spring)",
    "Pre Calculus, CP",
    "National & International Current Affairs (Fall) / Public Speaking (Spring)",
    "PE/Health (Fall) / PE/Health (Spring)",
    "AP English Language & Composition",
    "Calculus",
    "AP Physics I",
  
    // ===== Period 4 =====
    "US History, CP",
    "Biology, Honors",
    "PE/Health (Fall) / PE/Health (Spring)",
    "Spanish II, Honors",
    "Arabic II, CP",
    "Instrumental Music I (Fall) / Instrumental Music II(Spring)",
    "English 11",
    "AP Computer Science A",
    "AP Chemistry",
    "Financial Literacy (Fall)/ Intro to Business (Spring)",
    "Juniors Only with cumulative unweighted GPA 3.75 and above",
    "Seniors Only Independent Online Courses with a Supervisor (Fall) / Independent Online Courses with a Supervisor (Spring)",
    "Intro to World Religions, Mythology, and Belief Systems I (Fall) / Intro to World Religions, Mythology, and Belief",
    "Sociology (Fall)/Anthropology(Spring)",
  
    // ===== Period 5 =====
    "PE/Health (Fall) / PE/Health (Spring)",
    "English 9, Honors",
    "Pencil and Ink Illustration (Fall) / Drawing and Painting (Spring)",
    "US History, Honors",
    "Chemistry, CP",
    "Computer Programming I (Fall) / Computer Programming II (Spring)",
    "AP Biology",
    "AP Psychology",
    "Physics, CP/Honors",
    "AP Comparative Government and Politics",
    "Entrepreneurship / Marketing",
    "Pre Calculus, CP",
    "Calculus",
    "AP Calculus AB",
    "Principles of Business (Fall)/ Project Management (Spring)",
  
    // ===== Period 7 =====
    "English 9, CP",
    "US History, Honors",
    "Biology, Honors",
    "Algebra II",
    "Modern World History, Honors",
    "Pencil and Ink Illustration (Fall) / Drawing and Painting (Spring)",
    "English 10, CP",
    "AP US Government and Politics",
    "AP Macroeconomics",
    "AP Computer Science Principles",
    "Principles of Engineering (Fall)\nArchitectural CAD (Spring)",
    "Environmental Science",
    "English 12, Honors",
    "Honors Probability & Statistics",
  
    // ===== Period 8 =====
    "Digital Visual Art (Fall) / Animated Thinking (Spring)",
    "Instrumental Music I (Fall) / Instrumental Music II(Spring)",
    "Honors Spanish I",
    "Geometry, CP",
    "Algebra 2, Honors",
    "PE/Health (Fall) / PE/Health (Spring)",
    "Cultural Studies I/ Cultural Studies II",
    "Forensic Science (Fall)/ Introduction to Organic Chemistry (Spring)",
    "AP European History",
    "English 11, Honors",
    "AP Microeconomics",
    "AP Calculus BC",
    "English 12, Honors",
  ];

